"use client"

import { useState, useEffect } from "react"
import { AntiFraudBanner } from "@/components/anti-fraud-banner"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Building2, MapPin, DollarSign, Clock, Sparkles, Search } from "lucide-react"
import { PremiumModal } from "@/components/premium-modal"
import { useRouter } from "next/navigation"
import { getJobPostingDate, getJobPostedTimeAgo } from "@/lib/date-utils"
import { PersonalizedSummary } from "@/components/personalized-summary"

const jobsByCategory = {
  support: [
    {
      id: 1,
      title: "Assistente de Atendimento ao Cliente",
      company: "TechCorp International",
      location: "Estados Unidos",
      salary: "US$ 1.800 - 2.500",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 95,
    },
    {
      id: 2,
      title: "Suporte Técnico Remoto",
      company: "Global Solutions Ltd",
      location: "Canadá",
      salary: "CAD 2.200 - 3.000",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 94,
    },
    {
      id: 3,
      title: "Especialista em Suporte ao Cliente",
      company: "Customer First Inc",
      location: "Reino Unido",
      salary: "£ 1.900 - 2.600",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 93,
    },
    {
      id: 4,
      title: "Analista de Suporte Técnico",
      company: "Tech Support Pro",
      location: "Irlanda",
      salary: "€ 2.100 - 2.800",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 92,
    },
    {
      id: 5,
      title: "Coordenador de Atendimento",
      company: "Service Excellence",
      location: "Austrália",
      salary: "AUD 2.400 - 3.200",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 91,
    },
    {
      id: 6,
      title: "Agente de Suporte Multilíngue",
      company: "Global Support Services",
      location: "Portugal",
      salary: "€ 1.600 - 2.200",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 90,
    },
    {
      id: 7,
      title: "Especialista em Help Desk",
      company: "IT Solutions Group",
      location: "Estados Unidos",
      salary: "US$ 1.700 - 2.400",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 89,
    },
    {
      id: 8,
      title: "Analista de Customer Success",
      company: "Success Partners",
      location: "Reino Unido",
      salary: "£ 2.000 - 2.700",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 88,
    },
    {
      id: 9,
      title: "Consultor de Suporte Técnico",
      company: "Tech Consulting Inc",
      location: "Canadá",
      salary: "CAD 2.100 - 2.900",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 87,
    },
    {
      id: 10,
      title: "Supervisor de Atendimento",
      company: "Customer Care Solutions",
      location: "Irlanda",
      salary: "€ 2.300 - 3.100",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 86,
    },
    {
      id: 11,
      title: "Especialista em Suporte por Chat",
      company: "Chat Support Pro",
      location: "Estados Unidos",
      salary: "US$ 1.600 - 2.300",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 85,
    },
    {
      id: 12,
      title: "Analista de Qualidade de Atendimento",
      company: "Quality Assurance Group",
      location: "Austrália",
      salary: "AUD 2.200 - 3.000",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 84,
    },
    {
      id: 13,
      title: "Assistente de Suporte Remoto",
      company: "Remote Support Inc",
      location: "Portugal",
      salary: "€ 1.500 - 2.100",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 83,
    },
    {
      id: 14,
      title: "Coordenador de Help Desk",
      company: "Help Desk Solutions",
      location: "Reino Unido",
      salary: "£ 2.100 - 2.800",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 82,
    },
    {
      id: 15,
      title: "Especialista em Suporte de Software",
      company: "Software Support Co",
      location: "Canadá",
      salary: "CAD 2.000 - 2.800",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 81,
    },
    {
      id: 16,
      title: "Analista de Atendimento Digital",
      company: "Digital Customer Care",
      location: "Estados Unidos",
      salary: "US$ 1.800 - 2.500",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 80,
    },
    {
      id: 17,
      title: "Consultor de Customer Experience",
      company: "CX Consulting Group",
      location: "Irlanda",
      salary: "€ 2.200 - 3.000",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 79,
    },
    {
      id: 18,
      title: "Especialista em Suporte Técnico Nível 2",
      company: "Advanced Support Services",
      location: "Reino Unido",
      salary: "£ 2.200 - 2.900",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 78,
    },
    {
      id: 19,
      title: "Assistente de Customer Care",
      company: "Care Solutions International",
      location: "Austrália",
      salary: "AUD 2.100 - 2.900",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 77,
    },
    {
      id: 20,
      title: "Analista de Suporte ao Usuário",
      company: "User Support Group",
      location: "Canadá",
      salary: "CAD 1.900 - 2.700",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 76,
    },
    {
      id: 21,
      title: "Coordenador de Suporte Online",
      company: "Online Support Solutions",
      location: "Estados Unidos",
      salary: "US$ 2.000 - 2.700",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 75,
    },
    {
      id: 22,
      title: "Especialista em Atendimento B2B",
      company: "B2B Support Services",
      location: "Portugal",
      salary: "€ 1.700 - 2.400",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 74,
    },
    {
      id: 23,
      title: "Analista de Suporte Técnico Júnior",
      company: "Junior Tech Support",
      location: "Irlanda",
      salary: "€ 1.800 - 2.500",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 73,
    },
    {
      id: 24,
      title: "Assistente de Suporte por E-mail",
      company: "Email Support Pro",
      location: "Reino Unido",
      salary: "£ 1.700 - 2.400",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 72,
    },
    {
      id: 25,
      title: "Consultor de Atendimento ao Cliente",
      company: "Customer Consulting Inc",
      location: "Canadá",
      salary: "CAD 2.100 - 2.900",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 71,
    },
    {
      id: 26,
      title: "Especialista em Suporte Remoto",
      company: "Remote Tech Solutions",
      location: "Estados Unidos",
      salary: "US$ 1.900 - 2.600",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 70,
    },
    {
      id: 27,
      title: "Analista de Help Desk Internacional",
      company: "International Help Desk",
      location: "Austrália",
      salary: "AUD 2.300 - 3.100",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 69,
    },
    {
      id: 28,
      title: "Coordenador de Customer Success",
      company: "Success Coordination Group",
      location: "Portugal",
      salary: "€ 1.900 - 2.600",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 68,
    },
    {
      id: 29,
      title: "Especialista em Suporte Técnico Sênior",
      company: "Senior Support Services",
      location: "Reino Unido",
      salary: "£ 2.400 - 3.200",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 67,
    },
  ],
  admin: [
    {
      id: 30,
      title: "Assistente Administrativo Virtual",
      company: "European Services",
      location: "Portugal",
      salary: "€ 1.400 - 1.900",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 95,
    },
    {
      id: 31,
      title: "Assistente Financeiro",
      company: "Finance Global",
      location: "Suíça",
      salary: "CHF 2.500 - 3.500",
      currency: "CHF",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 94,
    },
    {
      id: 32,
      title: "Coordenador Administrativo",
      company: "Admin Solutions",
      location: "Estados Unidos",
      salary: "US$ 2.000 - 2.800",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 93,
    },
    {
      id: 33,
      title: "Analista de Processos",
      company: "Process Optimization",
      location: "Canadá",
      salary: "CAD 2.300 - 3.100",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 92,
    },
    {
      id: 34,
      title: "Assistente de Recursos Humanos",
      company: "HR Global Services",
      location: "Alemanha",
      salary: "€ 1.900 - 2.600",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 91,
    },
    {
      id: 35,
      title: "Analista Administrativo",
      company: "Administrative Excellence",
      location: "Reino Unido",
      salary: "£ 1.800 - 2.500",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 90,
    },
    {
      id: 36,
      title: "Assistente de Contabilidade",
      company: "Accounting Services Inc",
      location: "Estados Unidos",
      salary: "US$ 1.900 - 2.600",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 89,
    },
    {
      id: 37,
      title: "Coordenador de RH",
      company: "HR Coordination Group",
      location: "Irlanda",
      salary: "€ 2.100 - 2.900",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 88,
    },
    {
      id: 38,
      title: "Analista de Folha de Pagamento",
      company: "Payroll Solutions",
      location: "Canadá",
      salary: "CAD 2.200 - 3.000",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 87,
    },
    {
      id: 39,
      title: "Assistente de Compras",
      company: "Procurement Services",
      location: "Austrália",
      salary: "AUD 2.100 - 2.900",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 86,
    },
    {
      id: 40,
      title: "Coordenador Financeiro",
      company: "Financial Coordination",
      location: "Portugal",
      salary: "€ 1.800 - 2.500",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 85,
    },
    {
      id: 41,
      title: "Analista de Contas a Pagar",
      company: "Accounts Payable Group",
      location: "Reino Unido",
      salary: "£ 1.900 - 2.600",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 84,
    },
    {
      id: 42,
      title: "Assistente de Gestão de Documentos",
      company: "Document Management Co",
      location: "Estados Unidos",
      salary: "US$ 1.700 - 2.400",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 83,
    },
    {
      id: 43,
      title: "Coordenador de Operações",
      company: "Operations Management",
      location: "Canadá",
      salary: "CAD 2.100 - 2.900",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 82,
    },
    {
      id: 44,
      title: "Analista de Contas a Receber",
      company: "Accounts Receivable Services",
      location: "Irlanda",
      salary: "€ 2.000 - 2.700",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 81,
    },
    {
      id: 45,
      title: "Assistente de Planejamento",
      company: "Planning Solutions",
      location: "Alemanha",
      salary: "€ 1.900 - 2.600",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 80,
    },
    {
      id: 46,
      title: "Coordenador de Compliance",
      company: "Compliance Group",
      location: "Reino Unido",
      salary: "£ 2.100 - 2.800",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 79,
    },
    {
      id: 47,
      title: "Analista de Orçamento",
      company: "Budget Analysis Inc",
      location: "Estados Unidos",
      salary: "US$ 2.000 - 2.700",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 78,
    },
    {
      id: 48,
      title: "Assistente de Auditoria",
      company: "Audit Services Group",
      location: "Austrália",
      salary: "AUD 2.200 - 3.000",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 77,
    },
    {
      id: 49,
      title: "Coordenador de Facilities",
      company: "Facilities Management",
      location: "Canadá",
      salary: "CAD 2.000 - 2.800",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 76,
    },
    {
      id: 50,
      title: "Analista de Contratos",
      company: "Contract Management Co",
      location: "Portugal",
      salary: "€ 1.800 - 2.500",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 75,
    },
    {
      id: 51,
      title: "Assistente de Secretariado Executivo",
      company: "Executive Services",
      location: "Reino Unido",
      salary: "£ 2.000 - 2.700",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 74,
    },
    {
      id: 52,
      title: "Coordenador de Qualidade",
      company: "Quality Management Group",
      location: "Irlanda",
      salary: "€ 2.100 - 2.900",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 73,
    },
    {
      id: 53,
      title: "Analista de Relatórios Gerenciais",
      company: "Management Reporting Inc",
      location: "Estados Unidos",
      salary: "US$ 1.900 - 2.600",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 72,
    },
    {
      id: 54,
      title: "Assistente de Logística",
      company: "Logistics Solutions",
      location: "Canadá",
      salary: "CAD 1.900 - 2.700",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 71,
    },
    {
      id: 55,
      title: "Coordenador de Treinamento",
      company: "Training Coordination Group",
      location: "Austrália",
      salary: "AUD 2.100 - 2.900",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 70,
    },
    {
      id: 56,
      title: "Analista de Benefícios",
      company: "Benefits Administration",
      location: "Portugal",
      salary: "€ 1.700 - 2.400",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 69,
    },
    {
      id: 57,
      title: "Assistente de Recrutamento",
      company: "Recruitment Services",
      location: "Reino Unido",
      salary: "£ 1.800 - 2.500",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 68,
    },
    {
      id: 58,
      title: "Coordenador de Projetos Administrativos",
      company: "Admin Project Management",
      location: "Estados Unidos",
      salary: "US$ 2.100 - 2.800",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 67,
    },
  ],
  marketing: [
    {
      id: 59,
      title: "Especialista em Mídias Sociais",
      company: "Digital Marketing Pro",
      location: "Estados Unidos",
      salary: "US$ 1.600 - 2.200",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 96,
    },
    {
      id: 60,
      title: "Analista de Marketing Digital",
      company: "Marketing Innovations",
      location: "Reino Unido",
      salary: "£ 1.800 - 2.500",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 95,
    },
    {
      id: 61,
      title: "Redator de Conteúdo",
      company: "Content Masters",
      location: "Canadá",
      salary: "CAD 1.700 - 2.400",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 94,
    },
    {
      id: 62,
      title: "Especialista em SEO",
      company: "SEO Masters",
      location: "Irlanda",
      salary: "€ 2.000 - 2.800",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 93,
    },
    {
      id: 63,
      title: "Gerente de Comunidade",
      company: "Community Builders",
      location: "Portugal",
      salary: "€ 1.600 - 2.300",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 92,
    },
    {
      id: 64,
      title: "Coordenador de Marketing de Conteúdo",
      company: "Content Marketing Group",
      location: "Estados Unidos",
      salary: "US$ 1.900 - 2.600",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 91,
    },
    {
      id: 65,
      title: "Analista de Performance Digital",
      company: "Digital Performance Inc",
      location: "Austrália",
      salary: "AUD 2.200 - 3.000",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 90,
    },
    {
      id: 66,
      title: "Especialista em E-mail Marketing",
      company: "Email Marketing Pro",
      location: "Reino Unido",
      salary: "£ 1.700 - 2.400",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 89,
    },
    {
      id: 67,
      title: "Copywriter Digital",
      company: "Digital Copy Services",
      location: "Canadá",
      salary: "CAD 1.800 - 2.500",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 88,
    },
    {
      id: 68,
      title: "Coordenador de Campanhas",
      company: "Campaign Management Co",
      location: "Irlanda",
      salary: "€ 2.100 - 2.900",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 87,
    },
    {
      id: 69,
      title: "Analista de Mídias Pagas",
      company: "Paid Media Solutions",
      location: "Estados Unidos",
      salary: "US$ 2.000 - 2.700",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 86,
    },
    {
      id: 70,
      title: "Especialista em Growth Marketing",
      company: "Growth Marketing Group",
      location: "Portugal",
      salary: "€ 1.800 - 2.500",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 85,
    },
    {
      id: 71,
      title: "Coordenador de Branding",
      company: "Brand Management Inc",
      location: "Reino Unido",
      salary: "£ 2.000 - 2.700",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 84,
    },
    {
      id: 72,
      title: "Analista de Marketing de Produto",
      company: "Product Marketing Co",
      location: "Canadá",
      salary: "CAD 2.100 - 2.900",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 83,
    },
    {
      id: 73,
      title: "Especialista em Inbound Marketing",
      company: "Inbound Marketing Pro",
      location: "Austrália",
      salary: "AUD 2.100 - 2.900",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 82,
    },
    {
      id: 74,
      title: "Coordenador de Eventos Digitais",
      company: "Digital Events Group",
      location: "Estados Unidos",
      salary: "US$ 1.800 - 2.500",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 81,
    },
    {
      id: 75,
      title: "Analista de CRM",
      company: "CRM Solutions Inc",
      location: "Irlanda",
      salary: "€ 2.000 - 2.700",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 80,
    },
    {
      id: 76,
      title: "Especialista em Marketing de Afiliados",
      company: "Affiliate Marketing Co",
      location: "Reino Unido",
      salary: "£ 1.900 - 2.600",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 79,
    },
    {
      id: 77,
      title: "Coordenador de Influenciadores",
      company: "Influencer Marketing Group",
      location: "Canadá",
      salary: "CAD 1.900 - 2.700",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 78,
    },
    {
      id: 78,
      title: "Analista de Marketing Automation",
      company: "Marketing Automation Inc",
      location: "Portugal",
      salary: "€ 1.900 - 2.600",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 77,
    },
    {
      id: 79,
      title: "Especialista em Conversão",
      company: "Conversion Optimization Co",
      location: "Estados Unidos",
      salary: "US$ 2.100 - 2.800",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 76,
    },
    {
      id: 80,
      title: "Coordenador de Parcerias",
      company: "Partnership Management",
      location: "Austrália",
      salary: "AUD 2.200 - 3.000",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 75,
    },
    {
      id: 81,
      title: "Analista de Brand Marketing",
      company: "Brand Marketing Solutions",
      location: "Reino Unido",
      salary: "£ 2.100 - 2.800",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 74,
    },
    {
      id: 82,
      title: "Especialista em Marketing B2B",
      company: "B2B Marketing Group",
      location: "Irlanda",
      salary: "€ 2.200 - 3.000",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 73,
    },
    {
      id: 83,
      title: "Coordenador de Comunicação Digital",
      company: "Digital Communication Inc",
      location: "Canadá",
      salary: "CAD 2.000 - 2.800",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 72,
    },
    {
      id: 84,
      title: "Analista de Experiência do Cliente",
      company: "Customer Experience Co",
      location: "Estados Unidos",
      salary: "US$ 1.900 - 2.600",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 71,
    },
    {
      id: 85,
      title: "Especialista em Marketing de Vídeo",
      company: "Video Marketing Pro",
      location: "Portugal",
      salary: "€ 1.800 - 2.500",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 70,
    },
    {
      id: 86,
      title: "Coordenador de PR Digital",
      company: "Digital PR Group",
      location: "Reino Unido",
      salary: "£ 2.000 - 2.700",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 69,
    },
    {
      id: 87,
      title: "Analista de Marketing Analytics",
      company: "Marketing Analytics Inc",
      location: "Austrália",
      salary: "AUD 2.300 - 3.100",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 68,
    },
  ],
  sales: [
    {
      id: 88,
      title: "Assistente de Vendas Online",
      company: "E-commerce Plus",
      location: "Estados Unidos",
      salary: "US$ 1.500 - 2.100",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 95,
    },
    {
      id: 89,
      title: "Consultor de Vendas",
      company: "Sales Consulting Group",
      location: "Austrália",
      salary: "AUD 2.300 - 3.100",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 94,
    },
    {
      id: 90,
      title: "Representante Comercial",
      company: "Global Commerce",
      location: "Reino Unido",
      salary: "£ 2.000 - 2.800",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 93,
    },
    {
      id: 91,
      title: "Especialista em Inside Sales",
      company: "Sales Pro International",
      location: "Canadá",
      salary: "CAD 2.200 - 3.000",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 92,
    },
    {
      id: 92,
      title: "Coordenador de Vendas",
      company: "Sales Excellence",
      location: "Estados Unidos",
      salary: "US$ 1.900 - 2.700",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 91,
    },
    {
      id: 93,
      title: "Analista de Vendas",
      company: "Sales Analysis Group",
      location: "Irlanda",
      salary: "€ 2.000 - 2.700",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 90,
    },
    {
      id: 94,
      title: "Executivo de Contas",
      company: "Account Management Inc",
      location: "Reino Unido",
      salary: "£ 2.100 - 2.900",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 89,
    },
    {
      id: 95,
      title: "Especialista em Vendas B2B",
      company: "B2B Sales Solutions",
      location: "Canadá",
      salary: "CAD 2.300 - 3.100",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 88,
    },
    {
      id: 96,
      title: "Coordenador de Pré-Vendas",
      company: "Pre-Sales Group",
      location: "Portugal",
      salary: "€ 1.800 - 2.500",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 87,
    },
    {
      id: 97,
      title: "Analista de Business Development",
      company: "Business Development Co",
      location: "Estados Unidos",
      salary: "US$ 2.100 - 2.800",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 86,
    },
    {
      id: 98,
      title: "Especialista em Vendas SaaS",
      company: "SaaS Sales Pro",
      location: "Austrália",
      salary: "AUD 2.400 - 3.200",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 85,
    },
    {
      id: 99,
      title: "Coordenador de Relacionamento",
      company: "Relationship Management",
      location: "Reino Unido",
      salary: "£ 1.900 - 2.600",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 84,
    },
    {
      id: 100,
      title: "Analista de Propostas Comerciais",
      company: "Commercial Proposals Inc",
      location: "Canadá",
      salary: "CAD 2.000 - 2.800",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 83,
    },
    {
      id: 101,
      title: "Especialista em Vendas Consultivas",
      company: "Consultative Sales Group",
      location: "Irlanda",
      salary: "€ 2.100 - 2.900",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 82,
    },
    {
      id: 102,
      title: "Coordenador de Canais de Vendas",
      company: "Sales Channels Management",
      location: "Estados Unidos",
      salary: "US$ 2.000 - 2.700",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 81,
    },
    {
      id: 103,
      title: "Analista de Performance de Vendas",
      company: "Sales Performance Co",
      location: "Portugal",
      salary: "€ 1.900 - 2.600",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 80,
    },
    {
      id: 104,
      title: "Especialista em Vendas Digitais",
      company: "Digital Sales Solutions",
      location: "Reino Unido",
      salary: "£ 2.000 - 2.700",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 79,
    },
    {
      id: 105,
      title: "Coordenador de Vendas Internacionais",
      company: "International Sales Group",
      location: "Canadá",
      salary: "CAD 2.200 - 3.000",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 78,
    },
    {
      id: 106,
      title: "Analista de CRM de Vendas",
      company: "Sales CRM Solutions",
      location: "Austrália",
      salary: "AUD 2.200 - 3.000",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 77,
    },
    {
      id: 107,
      title: "Especialista em Vendas por Telefone",
      company: "Telesales Pro",
      location: "Estados Unidos",
      salary: "US$ 1.700 - 2.400",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 76,
    },
    {
      id: 108,
      title: "Coordenador de Expansão Comercial",
      company: "Commercial Expansion Co",
      location: "Irlanda",
      salary: "€ 2.200 - 3.000",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 75,
    },
    {
      id: 109,
      title: "Analista de Estratégia de Vendas",
      company: "Sales Strategy Group",
      location: "Reino Unido",
      salary: "£ 2.100 - 2.800",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 74,
    },
    {
      id: 110,
      title: "Especialista em Account Management",
      company: "Account Management Pro",
      location: "Canadá",
      salary: "CAD 2.100 - 2.900",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 73,
    },
    {
      id: 111,
      title: "Coordenador de Vendas Online",
      company: "Online Sales Solutions",
      location: "Portugal",
      salary: "€ 1.800 - 2.500",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 72,
    },
    {
      id: 112,
      title: "Analista de Funil de Vendas",
      company: "Sales Funnel Analytics",
      location: "Estados Unidos",
      salary: "US$ 1.900 - 2.600",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 71,
    },
    {
      id: 113,
      title: "Especialista em Vendas Corporativas",
      company: "Corporate Sales Group",
      location: "Austrália",
      salary: "AUD 2.500 - 3.300",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 70,
    },
    {
      id: 114,
      title: "Coordenador de Parcerias Comerciais",
      company: "Commercial Partnerships Inc",
      location: "Reino Unido",
      salary: "£ 2.000 - 2.700",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 69,
    },
    {
      id: 115,
      title: "Analista de Retenção de Clientes",
      company: "Customer Retention Co",
      location: "Irlanda",
      salary: "€ 2.000 - 2.700",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 68,
    },
    {
      id: 116,
      title: "Especialista em Vendas Técnicas",
      company: "Technical Sales Solutions",
      location: "Canadá",
      salary: "CAD 2.300 - 3.100",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 67,
    },
  ],
  tech: [
    {
      id: 117,
      title: "Desenvolvedor Web Júnior",
      company: "WebDev Agency",
      location: "Irlanda",
      salary: "€ 2.200 - 3.000",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 96,
    },
    {
      id: 118,
      title: "Designer Gráfico",
      company: "Creative Studio",
      location: "Canadá",
      salary: "CAD 2.000 - 2.800",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 95,
    },
    {
      id: 119,
      title: "Analista de Dados Júnior",
      company: "DataTech Solutions",
      location: "Reino Unido",
      salary: "£ 2.000 - 2.800",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 94,
    },
    {
      id: 120,
      title: "Especialista em UX/UI",
      company: "Design Innovations",
      location: "Estados Unidos",
      salary: "US$ 2.000 - 2.800",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 93,
    },
    {
      id: 121,
      title: "Editor de Vídeo",
      company: "Video Production Studio",
      location: "Portugal",
      salary: "€ 1.800 - 2.600",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 92,
    },
    {
      id: 122,
      title: "Desenvolvedor Front-End",
      company: "Frontend Solutions",
      location: "Austrália",
      salary: "AUD 2.400 - 3.200",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 91,
    },
    {
      id: 123,
      title: "Designer de Produto Digital",
      company: "Product Design Co",
      location: "Reino Unido",
      salary: "£ 2.100 - 2.900",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 90,
    },
    {
      id: 124,
      title: "Analista de QA",
      company: "Quality Assurance Group",
      location: "Canadá",
      salary: "CAD 2.100 - 2.900",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 89,
    },
    {
      id: 125,
      title: "Especialista em WordPress",
      company: "WordPress Solutions",
      location: "Estados Unidos",
      salary: "US$ 1.800 - 2.500",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 88,
    },
    {
      id: 126,
      title: "Designer de Interface",
      company: "Interface Design Studio",
      location: "Irlanda",
      salary: "€ 2.000 - 2.700",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 87,
    },
    {
      id: 127,
      title: "Desenvolvedor Mobile Júnior",
      company: "Mobile Dev Solutions",
      location: "Portugal",
      salary: "€ 2.100 - 2.900",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 86,
    },
    {
      id: 128,
      title: "Analista de Business Intelligence",
      company: "BI Solutions Group",
      location: "Reino Unido",
      salary: "£ 2.200 - 3.000",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 85,
    },
    {
      id: 129,
      title: "Especialista em Automação",
      company: "Automation Technologies",
      location: "Canadá",
      salary: "CAD 2.200 - 3.000",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 84,
    },
    {
      id: 130,
      title: "Designer de Experiência",
      company: "Experience Design Co",
      location: "Austrália",
      salary: "AUD 2.300 - 3.100",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 83,
    },
    {
      id: 131,
      title: "Desenvolvedor Back-End Júnior",
      company: "Backend Solutions",
      location: "Estados Unidos",
      salary: "US$ 2.100 - 2.800",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 82,
    },
    {
      id: 132,
      title: "Analista de Sistemas",
      company: "Systems Analysis Group",
      location: "Irlanda",
      salary: "€ 2.100 - 2.900",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 81,
    },
    {
      id: 133,
      title: "Especialista em E-commerce",
      company: "E-commerce Tech Solutions",
      location: "Reino Unido",
      salary: "£ 1.900 - 2.600",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 80,
    },
    {
      id: 134,
      title: "Designer de Motion Graphics",
      company: "Motion Design Studio",
      location: "Canadá",
      salary: "CAD 2.000 - 2.800",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 79,
    },
    {
      id: 135,
      title: "Desenvolvedor Full Stack Júnior",
      company: "Full Stack Solutions",
      location: "Portugal",
      salary: "€ 2.200 - 3.000",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 78,
    },
    {
      id: 136,
      title: "Analista de Segurança da Informação",
      company: "InfoSec Group",
      location: "Estados Unidos",
      salary: "US$ 2.300 - 3.100",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 77,
    },
    {
      id: 137,
      title: "Especialista em Cloud Computing",
      company: "Cloud Solutions Inc",
      location: "Austrália",
      salary: "AUD 2.500 - 3.300",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 76,
    },
    {
      id: 138,
      title: "Designer de Interfaces Mobile",
      company: "Mobile UI Design Co",
      location: "Reino Unido",
      salary: "£ 2.000 - 2.700",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 75,
    },
    {
      id: 139,
      title: "Desenvolvedor de Jogos Júnior",
      company: "Game Development Studio",
      location: "Canadá",
      salary: "CAD 2.100 - 2.900",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 74,
    },
    {
      id: 140,
      title: "Analista de DevOps",
      company: "DevOps Solutions Group",
      location: "Irlanda",
      salary: "€ 2.300 - 3.100",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 73,
    },
    {
      id: 141,
      title: "Especialista em Inteligência Artificial",
      company: "AI Technologies Inc",
      location: "Estados Unidos",
      salary: "US$ 2.500 - 3.300",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 72,
    },
    {
      id: 142,
      title: "Designer de Branding Digital",
      company: "Digital Branding Studio",
      location: "Portugal",
      salary: "€ 1.900 - 2.600",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 71,
    },
    {
      id: 143,
      title: "Desenvolvedor de APIs",
      company: "API Development Co",
      location: "Reino Unido",
      salary: "£ 2.100 - 2.900",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 70,
    },
    {
      id: 144,
      title: "Analista de Machine Learning",
      company: "ML Solutions Group",
      location: "Austrália",
      salary: "AUD 2.600 - 3.400",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 69,
    },
    {
      id: 145,
      title: "Especialista em Blockchain",
      company: "Blockchain Technologies",
      location: "Canadá",
      salary: "CAD 2.400 - 3.200",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 68,
    },
  ],
  other: [
    {
      id: 146,
      title: "Coordenador de Projetos",
      company: "Project Management Co",
      location: "Alemanha",
      salary: "€ 2.000 - 2.700",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 85,
    },
    {
      id: 147,
      title: "Assistente de Operações",
      company: "Operations Excellence",
      location: "Holanda",
      salary: "€ 1.900 - 2.600",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 84,
    },
    {
      id: 148,
      title: "Tradutor Inglês-Português",
      company: "Translation Services",
      location: "Portugal",
      salary: "€ 1.300 - 1.800",
      currency: "EUR",
      type: "Meio Período",
      posted: "5 horas atrás",
      match: 83,
    },
    {
      id: 149,
      title: "Coordenador de Eventos Virtuais",
      company: "Virtual Events Co",
      location: "Reino Unido",
      salary: "£ 1.600 - 2.300",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 82,
    },
    {
      id: 150,
      title: "Assistente de Pesquisa",
      company: "Research Institute",
      location: "Estados Unidos",
      salary: "US$ 1.800 - 2.500",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 81,
    },
    {
      id: 151,
      title: "Coordenador de Educação Online",
      company: "Online Education Group",
      location: "Canadá",
      salary: "CAD 2.000 - 2.800",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 80,
    },
    {
      id: 152,
      title: "Analista de Sustentabilidade",
      company: "Sustainability Solutions",
      location: "Irlanda",
      salary: "€ 2.100 - 2.900",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 79,
    },
    {
      id: 153,
      title: "Especialista em Experiência do Usuário",
      company: "UX Research Co",
      location: "Reino Unido",
      salary: "£ 2.000 - 2.700",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 78,
    },
    {
      id: 154,
      title: "Coordenador de Voluntariado",
      company: "Volunteer Management",
      location: "Austrália",
      salary: "AUD 2.100 - 2.900",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 77,
    },
    {
      id: 155,
      title: "Assistente de Biblioteca Digital",
      company: "Digital Library Services",
      location: "Portugal",
      salary: "€ 1.500 - 2.100",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 76,
    },
    {
      id: 156,
      title: "Coordenador de Inovação",
      company: "Innovation Hub",
      location: "Estados Unidos",
      salary: "US$ 2.100 - 2.800",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 75,
    },
    {
      id: 157,
      title: "Analista de Tendências",
      company: "Trend Analysis Group",
      location: "Canadá",
      salary: "CAD 2.000 - 2.800",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 74,
    },
    {
      id: 158,
      title: "Especialista em Acessibilidade",
      company: "Accessibility Solutions",
      location: "Reino Unido",
      salary: "£ 1.900 - 2.600",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 73,
    },
    {
      id: 159,
      title: "Coordenador de Diversidade",
      company: "Diversity & Inclusion Co",
      location: "Irlanda",
      salary: "€ 2.000 - 2.700",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 72,
    },
    {
      id: 160,
      title: "Assistente de Curadoria Digital",
      company: "Digital Curation Services",
      location: "Alemanha",
      salary: "€ 1.800 - 2.500",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 71,
    },
    {
      id: 161,
      title: "Coordenador de Bem-Estar",
      company: "Wellness Programs Inc",
      location: "Austrália",
      salary: "AUD 2.200 - 3.000",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 70,
    },
    {
      id: 162,
      title: "Analista de Impacto Social",
      company: "Social Impact Group",
      location: "Estados Unidos",
      salary: "US$ 1.900 - 2.600",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 69,
    },
    {
      id: 163,
      title: "Especialista em Gamificação",
      company: "Gamification Solutions",
      location: "Canadá",
      salary: "CAD 2.100 - 2.900",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 68,
    },
    {
      id: 164,
      title: "Coordenador de Mentoria",
      company: "Mentorship Programs Co",
      location: "Portugal",
      salary: "€ 1.700 - 2.400",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 67,
    },
    {
      id: 165,
      title: "Assistente de Produção de Conteúdo",
      company: "Content Production Studio",
      location: "Reino Unido",
      salary: "£ 1.800 - 2.500",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 66,
    },
    {
      id: 166,
      title: "Coordenador de Comunidades Online",
      company: "Online Communities Inc",
      location: "Irlanda",
      salary: "€ 1.900 - 2.600",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 65,
    },
    {
      id: 167,
      title: "Analista de Comportamento do Consumidor",
      company: "Consumer Insights Group",
      location: "Estados Unidos",
      salary: "US$ 2.000 - 2.700",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 64,
    },
    {
      id: 168,
      title: "Especialista em Storytelling",
      company: "Storytelling Agency",
      location: "Canadá",
      salary: "CAD 1.900 - 2.700",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 63,
    },
    {
      id: 169,
      title: "Coordenador de Podcasts",
      company: "Podcast Production Co",
      location: "Austrália",
      salary: "AUD 2.000 - 2.800",
      currency: "AUD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 62,
    },
    {
      id: 170,
      title: "Assistente de Pesquisa de Mercado",
      company: "Market Research Inc",
      location: "Reino Unido",
      salary: "£ 1.800 - 2.500",
      currency: "GBP",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 61,
    },
    {
      id: 171,
      title: "Coordenador de Webinars",
      company: "Webinar Solutions Group",
      location: "Portugal",
      salary: "€ 1.600 - 2.300",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 60,
    },
    {
      id: 172,
      title: "Analista de Feedback de Clientes",
      company: "Customer Feedback Co",
      location: "Estados Unidos",
      salary: "US$ 1.800 - 2.500",
      currency: "USD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 59,
    },
    {
      id: 173,
      title: "Especialista em Onboarding",
      company: "Onboarding Solutions",
      location: "Canadá",
      salary: "CAD 2.000 - 2.800",
      currency: "CAD",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 58,
    },
    {
      id: 174,
      title: "Coordenador de Newsletters",
      company: "Newsletter Management Co",
      location: "Irlanda",
      salary: "€ 1.700 - 2.400",
      currency: "EUR",
      type: "Tempo Integral",
      posted: "5 horas atrás",
      match: 57,
    },
  ],
}

const categoryMap: Record<string, keyof typeof jobsByCategory> = {
  support: "support",
  admin: "admin",
  marketing: "marketing",
  sales: "sales",
  tech: "tech",
  other: "other",
}

export default function JobsPage() {
  const router = useRouter()
  const [showPremiumModal, setShowPremiumModal] = useState(false)
  const [searchTerm, setSearchTerm] = useState("")
  const [filteredJobs, setFilteredJobs] = useState<(typeof jobsByCategory)[keyof typeof jobsByCategory]>([])
  const [hasScheduledInterview, setHasScheduledInterview] = useState(false)
  const [jobs, setJobs] = useState<(typeof jobsByCategory)[keyof typeof jobsByCategory]>([])

  useEffect(() => {
    const professionalArea = localStorage.getItem("professionalArea") || "other"
    const category = categoryMap[professionalArea] || "other"
    const categoryJobs = jobsByCategory[category]

    setJobs(categoryJobs)
    setFilteredJobs(categoryJobs)
  }, [])

  useEffect(() => {
    const scheduled = localStorage.getItem("hasScheduledInterview")
    if (scheduled === "true") {
      setHasScheduledInterview(true)
    }
  }, [])

  useEffect(() => {
    const filtered = jobs.filter(
      (job) =>
        job.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        job.company.toLowerCase().includes(searchTerm.toLowerCase()) ||
        job.location.toLowerCase().includes(searchTerm.toLowerCase()),
    )
    setFilteredJobs(filtered)
  }, [searchTerm, jobs])

  const handleJobClick = (jobId: number) => {
    if (hasScheduledInterview) {
      setShowPremiumModal(true)
    } else {
      // Assuming scheduling an interview is equivalent to viewing the job for now
      // In a real application, this would trigger a separate action
      localStorage.setItem("hasScheduledInterview", "true")
      setHasScheduledInterview(true)
      router.push(`/job/${jobId}`)
    }
  }

  return (
    <div className="min-h-screen bg-background">
      <AntiFraudBanner />

      <div className="container mx-auto px-4 py-8 md:py-16">
        <div className="max-w-5xl mx-auto space-y-8">
          <div className="text-center space-y-4 animate-fade-in-up">
            <div className="inline-flex items-center gap-2 bg-primary/10 text-primary px-4 py-2 rounded-full text-sm font-medium">
              <Sparkles className="h-4 w-4" />
              Vagas Selecionadas Para Você
            </div>
            <h1 className="text-3xl md:text-5xl font-bold">Suas Oportunidades Personalizadas</h1>
            <p className="text-lg text-muted-foreground">
              Encontramos <span className="font-bold text-primary">41 vagas</span> que combinam perfeitamente com seu
              perfil
            </p>
            <p className="text-sm text-muted-foreground">{getJobPostingDate()}</p>
          </div>

          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-muted-foreground" />
            <Input
              type="text"
              placeholder="Buscar por cargo, empresa ou localização..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10 h-12"
            />
          </div>

          <div className="mb-8">
            <PersonalizedSummary />
          </div>

          <div className="space-y-6">
            {filteredJobs.map((job) => (
              <Card key={job.id} className="p-6 md:p-8 hover:shadow-lg transition-shadow">
                <div className="space-y-6">
                  <div className="flex items-start justify-between gap-4">
                    <div className="space-y-2 flex-1">
                      <div className="flex items-center gap-3 flex-wrap">
                        <h3 className="text-xl md:text-2xl font-bold">{job.title}</h3>
                        <Badge variant="secondary" className="bg-primary/10 text-primary">
                          {job.match}% compatível
                        </Badge>
                      </div>
                      <div className="flex items-center gap-2 text-muted-foreground">
                        <Building2 className="h-4 w-4" />
                        <span className="font-medium">{job.company}</span>
                      </div>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div className="flex items-center gap-2 text-sm">
                      <MapPin className="h-4 w-4 text-muted-foreground" />
                      <span>{job.location}</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm">
                      <DollarSign className="h-4 w-4 text-muted-foreground" />
                      <span className="font-medium text-primary">{job.salary}/mês</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm">
                      <Clock className="h-4 w-4 text-muted-foreground" />
                      <span>{getJobPostedTimeAgo()}</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-3 pt-4 border-t">
                    <Button size="lg" className="flex-1 md:flex-none" onClick={() => handleJobClick(job.id)}>
                      Ver Detalhes e Agendar Entrevista
                    </Button>
                  </div>
                </div>
              </Card>
            ))}
          </div>

          {filteredJobs.length === 0 && (
            <div className="text-center py-12">
              <p className="text-muted-foreground">Nenhuma vaga encontrada com os critérios de busca.</p>
            </div>
          )}
        </div>
      </div>

      <PremiumModal open={showPremiumModal} onOpenChange={setShowPremiumModal} />
    </div>
  )
}
